# Generated by Django 6.0.3 on 2026-04-02 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_player_delete_tennisplayer'),
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='player1',
        ),
        migrations.RemoveField(
            model_name='set',
            name='player1_games',
        ),
        migrations.RemoveField(
            model_name='set',
            name='player2',
        ),
        migrations.RemoveField(
            model_name='set',
            name='player2_games',
        ),
        migrations.AddField(
            model_name='set',
            name='player_1',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sets_as_player_1', to='home.player'),
        ),
        migrations.AddField(
            model_name='set',
            name='player_1_games',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='set',
            name='player_2',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sets_as_player_2', to='home.player'),
        ),
        migrations.AddField(
            model_name='set',
            name='player_2_games',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
