# Generated by Django 6.0.3 on 2026-04-12 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_player_points_player_circle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='circle',
        ),
        migrations.RemoveField(
            model_name='player',
            name='user',
        ),
    ]
