# Generated by Django 6.0.3 on 2026-04-12 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_player_circle_remove_player_user'),
        ('player', '0004_player_alter_set_player_1_alter_set_player_2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Player',
        ),
    ]
